version: "2"
services:
    db:
        image: "postgres"
        ports:
          - "5432:5432"
        env_file:
            - postgres.env
    web:
        build: ./web
        ports:
            - "80:80"
#    app:
#        build: .
#        environment:
#          - BOOKSUM_DB_HOST=172.17.0.1:5432
#        ports:
#            - "8888:8888"
#            - "9990:9990"
